# Tensorflow Demo

## How Tensorflow Works

It is comprised of 2 main parts:
1. Graphs
2. Sessions

A TensorFlow graph is a representation of computations structured as a directed graph. Nodes in the graph represent operations, which are units of computation, and edges represent the flow of tensors, which are the data that moves between operations. Graphs define the structure of the computation but do not execute it.

A TensorFlow session provides an environment for executing the operations defined in a graph. It allocates resources, such as memory, and manages the execution order of operations. To execute a graph, it needs to be launched within a session. Sessions allow for the evaluation of tensors and the execution of operations, producing results. It allows the user to execute a part of the graph or the entire graph depending on the requirement.

Tensorflow 2.x uses eager mode execution by default, which is explained later.

In [1]:
# Importing tensorflow

import tensorflow as tf
tf.version

2025-05-21 10:57:49.534521: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1747805270.010091   84231 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1747805270.152696   84231 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1747805271.406337   84231 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1747805271.406363   84231 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1747805271.406365   84231 computation_placer.cc:177] computation placer alr

<module 'tensorflow._api.v2.version' from '/home/ankit/Work/Projects/ml-research-project/tf/lib/python3.11/site-packages/tensorflow/_api/v2/version/__init__.py'>

## Tensors

"A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes." 

Tensors are a fundemental apsect of TensorFlow. They are the main objects that are passed around and manipluated throughout the program. Each tensor represents a partialy defined computation that will eventually produce a value. TensorFlow programs work by building a graph of Tensor objects that details how tensors are related. Running different parts of the graph allow results to be generated.

Each tensor has a data type and a shape. 

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

Scalar -> 1 Value
Vector -> Multiple Values

In [2]:
string = tf.Variable("Hello World", tf.string)
number = tf.Variable(10, tf.int32)
floating = tf.Variable(3.141, tf.float64)

I0000 00:00:1747805302.180160   84231 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 2573 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5


## Rank/Degree of a Tensor

Rank is basically the dimensions of a tensor.

Rank 0 Tensor is a Scalar.
Rank 1 Tensor is a Vector.
Rank 2 Tensor is a Matrix.

In [3]:
# To find rank of a tensor

tf.rank(string)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [4]:
# Creating rank 1 and rank 2 tensors
r1 = tf.Variable(["Hello", "World"], tf.string)
r2 = tf.Variable([["Hello", "World"], ["Tensorflow", "Demo"]], tf.string)

print(tf.rank(r1))
print(tf.rank(r2))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


## Shape of a Tensor

Shape gives a row x column format specifying how many data items are there in a tensor

In [5]:
print(tf.shape(number))
print(tf.shape(r1))
print(tf.shape(r2))

tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor([2 2], shape=(2,), dtype=int32)


## Reshaping Tensors

In [6]:
# Creating a tensor of ones, can do the same with tf.zeros to create a tensor of zeros

t1 = tf.ones([1, 2, 3])
print(t1)

# JUST MAKE SURE NUMBER OF ELEMENTS IN ORIGINAL TENSOR AND RESHAPED TENSOR IS SAME
# TO DO THAT, MULTIPLY THE DIMENSIONS AND MAKE SURE ANSWER IS SAME FOR BOTH

# Reshape to a 2,3,1 tensor
t2 = tf.reshape(t1, [2, 3, 1])
print(t2)

# Reshape to a tensor of size 3, other dimensions to be detected automatically
t3 = tf.reshape(t1, [3, -1])
print(t3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


### Slicing Tensors
You may be familiar with the term "slice" in python and its use on lists, tuples etc. Well the slice operator can be used on tensors to select specific axes or elements.

When we slice or select elements from a tensor, we can use comma seperated values inside the set of square brackets. Each subsequent value refrences a different dimension of the tensor.

Ex: ```tensor[dim1, dim2, dim3]```

In [7]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32) 
print(tf.rank(tensor))
print(tensor.shape)

three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)


## Types of Tensors

Before we go to far, I will mention that there are diffent types of tensors. These are the most used and we will talk more in depth about each as they are used.

    Variable: tf.Variable; Mutable
    Constant: tf.constant; Immutable
    Placeholder: tf.placeholder; largely used in tf 1.x, not anymore as tf 2.x executes in eager mode by deafult
    SparseTensor: tf.sparse.SparseTensor; Used to store data with multitudes of zeroes/empty values in the data 

With the execption of Variable all these tensors are immuttable, meaning their value may not change during execution.

## Eager Execution

TensorFlow's eager execution is an imperative programming environment that evaluates operations immediately without building graphs. Operations return concrete values instead of constructing a computational graph to run later. This makes it easy to get started with TensorFlow and debug models.

With TensorFlow 2.x, Eager Execution is enabled by default. This allows TensorFlow code to be executed and evaluated line by line. Before version 2.x was released, Eager execution was disabled by default. This meant that every graph had to be run within a TensorFlow session. This only allowed for the entire graph to be run all at once and made it hard to debug the computation graph.

Eager execution is a flexible machine learning platform for research and experimentation, which provides:

- An intuitive interface - Structure your code naturally and use Python data structures. Quickly iterate on small models and small data.
- Easier debugging - Execute operations directly to inspect code line by line and test changes. Use standard Python debugging tools for immediate error reporting.
- Natural control flow — Use Python control flow instead of graph control flow, simplifying the specification of dynamic models.

Eager execution is much easier to develop and debug code, while to get better efficiency, ability to run tensorflow code on distributed systems and systems with no python interpreters, Graph execution is better, as it makes a graph model that can be exported.

Graph Execution is an example of lazy execution.

So, **Develop in eager mode & then convert to Graph for deployment for the best results**.

# Diabetes Dataset(Binary Classification)

In [8]:
# Importing required packages

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf